---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: iap
spec:
  interval: 12h
  url: https://cloudnative-pg.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: iap
spec:
  interval: 12h
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.26.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: iap
  upgrade:
    cleanupOnFail: true
  values:
    crds:
      create: true