---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: iap
spec:
  chart:
    spec:
      chart: keycloak
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudpirates-keycloak
        namespace: iap
      version: 0.7.0
  interval: 10m0s
  values:
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      hosts:
        - host: auth.simonlk.dk
          paths:
            - path: /
              pathType: Prefix
    tls:
      enabled: true
      cert-manager:
        enabled: true
        issuerRef:
          name: "letsencrypt"
          kind: ClusterIssuer
    keycloak:
      httpEnabled: false
      production: true
      hostname: auth.simonlk.dk
      existingSecret: "keycloak-credentials"
      secretKeys:
        adminPasswordKey: "admin-password"
    database:
      type: "postgres"
      host: "keycloakdb.iap.svc.cluster.local"
      port: "5432"
      name: "keycloakdb"
      existingSecret: "keycloak-db-credentials"
      secretKeys:
        passwordKey: "username"
        usernameKey: "password"
    postgres:
      enabled: false
    mariadb:
      enabled: false
